import Head from 'next/head';
import { useQuery } from 'urql';
import { PRODUCT_QUERY } from '../lib/query';
import Product from '../components/Product';

const Home = () => {
    // Fetch products from strapi

    const [results] = useQuery({ query: PRODUCT_QUERY });
    const { data, fetching, error } = results;

    if (fetching) return <p>Loading...</p>;
    if (error) return <p>Oh no... {error.message}</p>;
    const products = data.products.data;
    console.log(products);

    return (
        <div>
            <Head>
                <title>E-Commerce Sneakers</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <h1>Next JS</h1>
                {products.map((product) => (
                    <Product key={product.attributes.slug} product={product} />
                ))}
            </main>
        </div>
    );
};

export default Home;
