import Image from 'next/image';
import { TickerWrapper } from '../../styles/HomePageStyles';

const Tickers = () => {
    return (
        <TickerWrapper>
            <div className="marquee">
                <div className="marquee__group">
                    <img
                        className="marquee__group_image"
                        src="/images/01.png"
                        alt="Hello"
                    />
                    <img
                        className="marquee__group_image"
                        src="/images/02.png"
                        alt="Hello"
                    />
                    <img
                        className="marquee__group_image"
                        src="/images/03.png"
                        alt="Hello"
                    />
                    <img
                        className="marquee__group_image"
                        src="/images/04.png"
                        alt="Hello"
                    />
                    <img
                        className="marquee__group_image"
                        src="/images/05.png"
                        alt="Hello"
                    />
                    <img
                        className="marquee__group_image"
                        src="/images/06.png"
                        alt="Hello"
                    />
                    <img
                        className="marquee__group_image"
                        src="/images/07.png"
                        alt="Hello"
                    />
                    <img
                        className="marquee__group_image"
                        src="/images/08.png"
                        alt="Hello"
                    />
                    <img
                        className="marquee__group_image"
                        src="/images/09.png"
                        alt="Hello"
                    />
                    <img
                        className="marquee__group_image"
                        src="/images/10.png"
                        alt="Hello"
                    />
                </div>
            </div>

            <div className="marquee__reverse">
                <div className="marquee__group">
                    <img
                        className="marquee__group_image"
                        src="/images/01.png"
                        alt="Hello"
                    />
                    <img
                        className="marquee__group_image"
                        src="/images/02.png"
                        alt="Hello"
                    />
                    <img
                        className="marquee__group_image"
                        src="/images/03.png"
                        alt="Hello"
                    />
                    <img
                        className="marquee__group_image"
                        src="/images/04.png"
                        alt="Hello"
                    />
                    <img
                        className="marquee__group_image"
                        src="/images/05.png"
                        alt="Hello"
                    />
                    <img
                        className="marquee__group_image"
                        src="/images/06.png"
                        alt="Hello"
                    />
                    <img
                        className="marquee__group_image"
                        src="/images/07.png"
                        alt="Hello"
                    />
                    <img
                        className="marquee__group_image"
                        src="/images/08.png"
                        alt="Hello"
                    />
                    <img
                        className="marquee__group_image"
                        src="/images/09.png"
                        alt="Hello"
                    />
                    <img
                        className="marquee__group_image"
                        src="/images/10.png"
                        alt="Hello"
                    />
                </div>
            </div>

            <div className="marquee">
                <div className="marquee__group">
                    <img
                        className="marquee__group_image"
                        src="/images/01.png"
                        alt="Hello"
                    />
                    <img
                        className="marquee__group_image"
                        src="/images/02.png"
                        alt="Hello"
                    />
                    <img
                        className="marquee__group_image"
                        src="/images/03.png"
                        alt="Hello"
                    />
                    <img
                        className="marquee__group_image"
                        src="/images/04.png"
                        alt="Hello"
                    />
                    <img
                        className="marquee__group_image"
                        src="/images/05.png"
                        alt="Hello"
                    />
                    <img
                        className="marquee__group_image"
                        src="/images/06.png"
                        alt="Hello"
                    />
                    <img
                        className="marquee__group_image"
                        src="/images/07.png"
                        alt="Hello"
                    />
                    <img
                        className="marquee__group_image"
                        src="/images/08.png"
                        alt="Hello"
                    />
                    <img
                        className="marquee__group_image"
                        src="/images/09.png"
                        alt="Hello"
                    />
                    <img
                        className="marquee__group_image"
                        src="/images/10.png"
                        alt="Hello"
                    />
                </div>
            </div>

            <div className="marquee__reverse">
                <div className="marquee__group">
                    <img
                        className="marquee__group_image"
                        src="/images/01.png"
                        alt="Hello"
                    />
                    <img
                        className="marquee__group_image"
                        src="/images/02.png"
                        alt="Hello"
                    />
                    <img
                        className="marquee__group_image"
                        src="/images/03.png"
                        alt="Hello"
                    />
                    <img
                        className="marquee__group_image"
                        src="/images/04.png"
                        alt="Hello"
                    />
                    <img
                        className="marquee__group_image"
                        src="/images/05.png"
                        alt="Hello"
                    />
                    <img
                        className="marquee__group_image"
                        src="/images/06.png"
                        alt="Hello"
                    />
                    <img
                        className="marquee__group_image"
                        src="/images/07.png"
                        alt="Hello"
                    />
                    <img
                        className="marquee__group_image"
                        src="/images/08.png"
                        alt="Hello"
                    />
                    <img
                        className="marquee__group_image"
                        src="/images/09.png"
                        alt="Hello"
                    />
                    <img
                        className="marquee__group_image"
                        src="/images/10.png"
                        alt="Hello"
                    />
                </div>
            </div>
        </TickerWrapper>
    );
};

export default Tickers;
